language: node_js
node_js:
  - '4'

sudo: false

install:
  - npm install -g serverless@1.0.0-rc.1
  - npm install serverless-offline --save-dev
  - npm install --save serverless-dynamodb-local
  - npm install --save dynamodb-doc-client-wrapper
  - npm install --save-dev mocha
  - npm install aws-sdk
  - npm install should --save-dev
  - npm install --save expect
  - travis_retry npm install

before_script:
  - sls dynamodb install
  - sls dynamodb start
  
script:
  - npm test
