language: node_js
node_js:
  - '4'

sudo: false

install:
  - npm install -g serverless@1.0.0-rc.1
  - npm install aws-sdk
  - serverless create --template aws-nodejs
  - npm link
  - cd node_modules/dynamodb-localhost
  - npm link serverless-dynamodb-local
  - npm install --save-dev serverless-offline 
  - npm install --save dynamodb-doc-client-wrapper
  - npm install --save-dev mocha
  - npm install --save-dev should
  - npm install --save expect
  - npm install --save request
  - npm install --save chai
  - travis_retry npm install

before_script:
  - sed -i '18 a Plugins:' serverless.yml
  - sed -i '19 a - serverless-offline' serverless.yml
  - sed -i '20 a - serverless-dynamodb-local' serverless.yml
  - sls dynamodb install
  - sls dynamodb start
  
script:
  - npm test
